services:
  app:
    build: .
    image: stationare-app:latest
    ports:
      - "8501:8501"
    environment:

      FM_API_BASE: "https://api.fm-track.com"
      EVENTS_BASE: "http://192.168.88.175:9877/api"
      TZ: "Europe/Bucharest"
    # Linuxon kellhet ez, hogy a host.docker.internal működjön
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 5s
      retries: 3
